map_file: "arena.map"
map_obstacle_height: 1.5
resolution: 0.5
origin: [-10.0, -10.0]

spawn:
  robots: 2
  pattern: "grid"         # grid | random_free
  # start_region fallback if there is no start_position passed in
  start_region: {xmin: -5, xmax: 5, ymin: -5, ymax: 5}
  robot_spacing: 1.1
  robot_clearance: 1.1
